sudo: required
language: cpp
services:
  - docker

before_install:
  - docker build -t tl-mr3020-toolchain .
  
script:
  - docker run --rm -t -i tl-mr3020-toolchain /bin/sh -c "cd /openwrt; FORCE_UNSAFE_CONFIGURE=1 make -j1 V=s"
